version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.9
  - dependency-name: ini
    versions:
    - 2.0.0
  - dependency-name: tailwindcss
    versions:
    - 2.0.4
