name: CD to GHP v3

on: 
  push:
    branches:
      - GHAtesting #should be dev
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: Install dependencies & compile code
        run: |
          git pull origin dev
          ls -la
          npm install
          ls -la
          npm run build
          ls -la 
      # Configures git credentials before pushing up to target branch
      - name: Package new compiled code & deploy to target branch
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Automatic build deployment"
          git push -fq

