name: Build & Deploy

on: 
  push:
    branches:
      - GHAtesting
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      
      - name: Compile code
        run: |
          npm install
          npm run build

      # List
      - name: List directory
        run: ls -all
      
      # Save compiled code as artifact
      - name: Upload built directory
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./*
          # Amount of days an artifact is stored before being deleted
          retention-days: 1

      - uses: actions/checkout@v2
        with:
          ref: prod

      # List
      - name: List directory
        run: ls -all

      # Download new compiled code artifact
      - name: Download compiled dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          # Download into current project directory
          path: ~/*

      - name: Move compiled code artifact into working directory
        run: mv ~/* ./

      # List
      - name: List directory
        run: ls -all

      # Configures git credentials before pushing up to target branch
      - name: Package new compiled code & deploy to target branch
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Automatic build deployment"
          git status
      
      # List
      - name: List directory
        run: ls -all